### PR TITLE
change id to _id

### PR DESCRIPTION
**Pull request by Webgardener**

### CODE REVIEW

**Comment by ptondereau** [comment]
@Webgardener can you be more explicit about your PR please ?

**Comment by Webgardener** [comment]
replacing id by _id is more convenient to implement the plateform api server. It indeed uses mongodb as a database.

**Comment by spyl94** [comment]
I don't think the specification should be driven by internal implementations such as mongodb. Using `id` as identifier is the standard of most apis.

**Comment by Webgardener** [comment]
You're right. I close the PR

**Pull request closed without merging**
